-- ARN Inventory backend foundation. Run in Supabase SQL Editor for the ARN Store Part Stock project.
create extension if not exists pgcrypto;
create table if not exists public.arn_accounts(id uuid primary key default gen_random_uuid(),name text not null default 'ARN Store',created_at timestamptz not null default now());
create table if not exists public.arn_profiles(id uuid primary key references auth.users(id) on delete cascade,account_id uuid not null references public.arn_accounts(id) on delete cascade,display_name text,role text not null default 'user' check(role in('user','admin')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.arn_categories(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.arn_accounts(id) on delete cascade,name text not null,is_active boolean not null default true,created_at timestamptz not null default now(),unique(account_id,name));
create table if not exists public.arn_parts(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.arn_accounts(id) on delete cascade,name text not null,code text,category_id uuid references public.arn_categories(id),unit text not null default 'pcs',purchase_price numeric,sale_price numeric,is_active boolean not null default true,master_source text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.arn_part_compatibilities(id uuid primary key default gen_random_uuid(),part_id uuid not null references public.arn_parts(id) on delete cascade,model text not null,normalized_model text not null,source text,created_at timestamptz not null default now(),unique(part_id,normalized_model));
create table if not exists public.arn_stock_transactions(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.arn_accounts(id) on delete cascade,part_id uuid not null references public.arn_parts(id),transaction_type text not null check(transaction_type in('in','out')),quantity integer not null check(quantity>0),reason text,movement_date date not null default current_date,supplier text,customer text,phone_model text,description text,purchase_price numeric,sale_price numeric,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.arn_license_codes(code text primary key,plan text not null check(plan in('user','admin')),duration_days integer,account_id uuid references public.arn_accounts(id),is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.arn_account_licenses(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.arn_accounts(id) on delete cascade,license_type text not null check(license_type in('demo','user','admin')),starts_at timestamptz not null default now(),expires_at timestamptz,is_active boolean not null default true,created_at timestamptz not null default now());
create or replace view public.arn_current_stock as select p.id part_id,p.account_id,p.name,p.code,p.category_id,p.unit,p.purchase_price,p.sale_price,p.is_active,coalesce(sum(case when t.transaction_type='in' then t.quantity when t.transaction_type='out' then -t.quantity else 0 end),0)::integer stock_quantity,case when coalesce(sum(case when t.transaction_type='in' then t.quantity when t.transaction_type='out' then -t.quantity else 0 end),0)>5 then 'Normal' when coalesce(sum(case when t.transaction_type='in' then t.quantity when t.transaction_type='out' then -t.quantity else 0 end),0)>0 then 'Menipis' else 'Kosong' end stock_status from public.arn_parts p left join public.arn_stock_transactions t on t.part_id=p.id group by p.id;
-- RLS is intentionally part of the production setup; policies should be reviewed in the project before enabling writes.
